// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/** Content for Template documents */
interface TemplateDocumentData {
  /**
   * Title field in *Template*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: template.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismic.RichTextField;
}
/**
 * Template document from Prismic
 *
 * - **API ID**: `template`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TemplateDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TemplateDocumentData>,
    "template",
    Lang
  >;
export type AllDocumentTypes = TemplateDocument;
/**
 * Primary content in SelfExplorationCtaLinks → Primary
 *
 */
interface SelfExplorationCtaLinksSliceDefaultPrimary {
  /**
   * Headline field in *SelfExplorationCtaLinks → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: self_exploration_cta_links.primary.headline
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  headline: prismic.RichTextField;
  /**
   * CTALink1 field in *SelfExplorationCtaLinks → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: self_exploration_cta_links.primary.ctalink1
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  ctalink1: prismic.LinkField;
  /**
   * CTALink2 field in *SelfExplorationCtaLinks → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: self_exploration_cta_links.primary.ctalink2
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  ctalink2: prismic.LinkField;
  /**
   * CTALink3 field in *SelfExplorationCtaLinks → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: self_exploration_cta_links.primary.ctalink3
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  ctalink3: prismic.LinkField;
}
/**
 * Default variation for SelfExplorationCtaLinks Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SelfExplorationCtaLinksSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SelfExplorationCtaLinksSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *SelfExplorationCtaLinks*
 *
 */
type SelfExplorationCtaLinksSliceVariation =
  SelfExplorationCtaLinksSliceDefault;
/**
 * SelfExplorationCtaLinks Shared Slice
 *
 * - **API ID**: `self_exploration_cta_links`
 * - **Description**: `SelfExplorationCtaLinks`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SelfExplorationCtaLinksSlice = prismic.SharedSlice<
  "self_exploration_cta_links",
  SelfExplorationCtaLinksSliceVariation
>;
declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }
  namespace Content {
    export type {
      TemplateDocumentData,
      TemplateDocument,
      AllDocumentTypes,
      SelfExplorationCtaLinksSliceDefaultPrimary,
      SelfExplorationCtaLinksSliceDefault,
      SelfExplorationCtaLinksSliceVariation,
      SelfExplorationCtaLinksSlice,
    };
  }
}
