// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  self_exploration_cta_links: dynamic(
    () => import("./SelfExplorationCtaLinks")
  ),
};
